category: Basic
case_code: 2DML
cfg_path: VandV/Basic/2DML/config_sa_restart.cfg
options:
  SOLVER: REPLACE_ME_FOR_SOLVER
  KIND_TURB_MODEL: REPLACE_ME_FOR_KIND_TURB_MODEL
  SA_OPTIONS: REPLACE_ME_FOR_SA_OPTIONS
  REF_DIMENSIONALIZATION: REPLACE_ME_FOR_REF_DIMENSIONALIZATION
  RESTART_SOL: REPLACE_ME_FOR_RESTART_SOL
  MACH_NUMBER: REPLACE_ME_FOR_MACH_NUMBER
  AOA: REPLACE_ME_FOR_AOA
  SIDESLIP_ANGLE: REPLACE_ME_FOR_SIDESLIP_ANGLE
  INIT_OPTION: REPLACE_ME_FOR_INIT_OPTION
  FREESTREAM_OPTION: REPLACE_ME_FOR_FREESTREAM_OPTION
  FREESTREAM_TEMPERATURE: REPLACE_ME_FOR_FREESTREAM_TEMPERATURE
  FREESTREAM_PRESSURE: REPLACE_ME_FOR_FREESTREAM_PRESSURE
  REYNOLDS_LENGTH: REPLACE_ME_FOR_REYNOLDS_LENGTH
  REF_AREA: REPLACE_ME_FOR_REF_AREA
  REF_LENGTH: REPLACE_ME_FOR_REF_LENGTH
  REF_ORIGIN_MOMENT_X: REPLACE_ME_FOR_REF_ORIGIN_MOMENT_X
  REF_ORIGIN_MOMENT_Y: REPLACE_ME_FOR_REF_ORIGIN_MOMENT_Y
  REF_ORIGIN_MOMENT_Z: REPLACE_ME_FOR_REF_ORIGIN_MOMENT_Z
  MARKER_SYM: REPLACE_ME_FOR_MARKER_SYM
  MARKER_INLET: REPLACE_ME_FOR_MARKER_INLET
  MARKER_OUTLET: REPLACE_ME_FOR_MARKER_OUTLET
  MARKER_HEATFLUX: REPLACE_ME_FOR_MARKER_HEATFLUX
  MARKER_PLOTTING: REPLACE_ME_FOR_MARKER_PLOTTING
  MARKER_MONITORING: REPLACE_ME_FOR_MARKER_MONITORING
  FLUID_MODEL: REPLACE_ME_FOR_FLUID_MODEL
  GAMMA_VALUE: REPLACE_ME_FOR_GAMMA_VALUE
  GAS_CONSTANT: REPLACE_ME_FOR_GAS_CONSTANT
  VISCOSITY_MODEL: REPLACE_ME_FOR_VISCOSITY_MODEL
  MU_REF: REPLACE_ME_FOR_MU_REF
  MU_T_REF: REPLACE_ME_FOR_MU_T_REF
  SUTHERLAND_CONSTANT: REPLACE_ME_FOR_SUTHERLAND_CONSTANT
  CONDUCTIVITY_MODEL: REPLACE_ME_FOR_CONDUCTIVITY_MODEL
  PRANDTL_LAM: REPLACE_ME_FOR_PRANDTL_LAM
  PRANDTL_TURB: REPLACE_ME_FOR_PRANDTL_TURB
  NUM_METHOD_GRAD: REPLACE_ME_FOR_NUM_METHOD_GRAD
  CFL_NUMBER: REPLACE_ME_FOR_CFL_NUMBER
  CFL_ADAPT: REPLACE_ME_FOR_CFL_ADAPT
  CFL_ADAPT_PARAM: REPLACE_ME_FOR_CFL_ADAPT_PARAM
  ITER: REPLACE_ME_FOR_ITER
  LINEAR_SOLVER: REPLACE_ME_FOR_LINEAR_SOLVER
  LINEAR_SOLVER_ERROR: REPLACE_ME_FOR_LINEAR_SOLVER_ERROR
  LINEAR_SOLVER_ITER: REPLACE_ME_FOR_LINEAR_SOLVER_ITER
  CONV_NUM_METHOD_FLOW: REPLACE_ME_FOR_CONV_NUM_METHOD_FLOW
  MUSCL_FLOW: REPLACE_ME_FOR_MUSCL_FLOW
  SLOPE_LIMITER_FLOW: REPLACE_ME_FOR_SLOPE_LIMITER_FLOW
  VENKAT_LIMITER_COEFF: REPLACE_ME_FOR_VENKAT_LIMITER_COEFF
  JST_SENSOR_COEFF: REPLACE_ME_FOR_JST_SENSOR_COEFF
  TIME_DISCRE_FLOW: REPLACE_ME_FOR_TIME_DISCRE_FLOW
  CONV_NUM_METHOD_TURB: REPLACE_ME_FOR_CONV_NUM_METHOD_TURB
  MUSCL_TURB: REPLACE_ME_FOR_MUSCL_TURB
  SLOPE_LIMITER_TURB: REPLACE_ME_FOR_SLOPE_LIMITER_TURB
  TIME_DISCRE_TURB: REPLACE_ME_FOR_TIME_DISCRE_TURB
  CFL_REDUCTION_TURB: REPLACE_ME_FOR_CFL_REDUCTION_TURB
  CONV_RESIDUAL_MINVAL: REPLACE_ME_FOR_CONV_RESIDUAL_MINVAL
  CONV_STARTITER: REPLACE_ME_FOR_CONV_STARTITER
  CONV_CAUCHY_ELEMS: REPLACE_ME_FOR_CONV_CAUCHY_ELEMS
  CONV_CAUCHY_EPS: REPLACE_ME_FOR_CONV_CAUCHY_EPS
  MESH_FILENAME: REPLACE_ME_FOR_MESH_FILENAME
  MESH_FORMAT: REPLACE_ME_FOR_MESH_FORMAT
  SOLUTION_FILENAME: REPLACE_ME_FOR_SOLUTION_FILENAME
  OUTPUT_WRT_FREQ: REPLACE_ME_FOR_OUTPUT_WRT_FREQ
  SCREEN_WRT_FREQ_INNER: REPLACE_ME_FOR_SCREEN_WRT_FREQ_INNER
  HISTORY_OUTPUT: REPLACE_ME_FOR_HISTORY_OUTPUT
  SCREEN_OUTPUT: REPLACE_ME_FOR_SCREEN_OUTPUT

