category: Basic
case_code: 2DML
cfg_path: VandV/Basic/2DML/config_sa_restart.cfg
options:
  SOLVER: RANS
  KIND_TURB_MODEL: SA
  SA_OPTIONS: NONE
  REF_DIMENSIONALIZATION: DIMENSIONAL
  RESTART_SOL: YES
  MACH_NUMBER: 0.12
  AOA: 0
  SIDESLIP_ANGLE: 0.0
  INIT_OPTION: TD_CONDITIONS
  FREESTREAM_OPTION: TEMPERATURE_FS
  FREESTREAM_TEMPERATURE: 293.0
  FREESTREAM_PRESSURE: 101325
  REYNOLDS_LENGTH: 1.0
  REF_AREA: 1.0
  REF_LENGTH: 1.0
  REF_ORIGIN_MOMENT_X: 0.0
  REF_ORIGIN_MOMENT_Y: 0.0
  REF_ORIGIN_MOMENT_Z: 0.0
  MARKER_SYM: ( SymmetryLower, SymmetryUpper )
  MARKER_INLET: ( InletLower, 293.24905, 101627.96175, 1.0, 0.0, 0.0, InletUpper, 293.85849, 102369.66, 1.0, 0.0, 0.0 )
  MARKER_OUTLET: ( Outlet, 101325 )
  MARKER_HEATFLUX: ( WallLower, 0.0, WallTip, 0.0, WallUpper, 0.0 )
  MARKER_PLOTTING: ( WallLower, WallTip, WallUpper )
  MARKER_MONITORING: ( WallLower, WallTip, WallUpper )
  FLUID_MODEL: STANDARD_AIR
  GAMMA_VALUE: 1.4
  GAS_CONSTANT: 287.05
  VISCOSITY_MODEL: SUTHERLAND
  MU_REF: 1.716E-5
  MU_T_REF: 273.15
  SUTHERLAND_CONSTANT: 110.4
  CONDUCTIVITY_MODEL: CONSTANT_PRANDTL
  PRANDTL_LAM: 0.72
  PRANDTL_TURB: 0.90
  NUM_METHOD_GRAD: WEIGHTED_LEAST_SQUARES
  CFL_NUMBER: 100.0
  CFL_ADAPT: NO
  CFL_ADAPT_PARAM: ( 1.5, 0.5, 1.0, 100.0 )
  ITER: 100000
  LINEAR_SOLVER: FGMRES
  LINEAR_SOLVER_ERROR: 1E-4
  LINEAR_SOLVER_ITER: 2
  CONV_NUM_METHOD_FLOW: ROE
  MUSCL_FLOW: YES
  SLOPE_LIMITER_FLOW: NO
  VENKAT_LIMITER_COEFF: VENKATAKRISHNAN_WANG
  JST_SENSOR_COEFF: NONE
  TIME_DISCRE_FLOW: 0.03
  CONV_NUM_METHOD_TURB: ( 0.5, 0.02 )
  MUSCL_TURB: EULER_IMPLICIT
  SLOPE_LIMITER_TURB: SCALAR_UPWIND
  TIME_DISCRE_TURB: NO
  CFL_REDUCTION_TURB: VENKATAKRISHNAN_WANG
  CONV_RESIDUAL_MINVAL: EULER_IMPLICIT
  CONV_STARTITER: 1.0
  CONV_CAUCHY_ELEMS: -8
  CONV_CAUCHY_EPS: 10
  MESH_FILENAME:  047.su2
  MESH_FORMAT:  SU2
  SOLUTION_FILENAME: restart.dat
  OUTPUT_WRT_FREQ: 500
  SCREEN_WRT_FREQ_INNER: 1
  HISTORY_OUTPUT: ( ITER, RMS_RES, AERO_COEFF )
  SCREEN_OUTPUT:  ( INNER_ITER, RMS_RES, FORCE_X, FORCE_Y, FORCE_Z )

