name: Select Validation Case

on:
  workflow_dispatch:
    inputs:
      case_code:
        description: "Enter the Validation Case Code (e.g., 2DZP)"
        required: true
        type: string

jobs:
  prepare-config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Parse config and commit metadata
        run: |
          CASE_CODE="${{ github.event.inputs.case_code }}"
          CONFIG_PATH="VandV/$CASE_CODE/config_sa_restart.cfg"

          if [ ! -f "$CONFIG_PATH" ]; then
            echo "::error::Config file not found at $CONFIG_PATH"
            exit 1
          fi

          echo "Parsing $CONFIG_PATH"

          mkdir -p .ci/cache/$CASE_CODE

          # Extract keys and comments for UI
          grep -E '^[^#%].*=' "$CONFIG_PATH" | awk -F '=' '{print $1}' | sed 's/ *$//' \
            | jq -R -s -c 'split("\n") | map(select(length > 0))' > .ci/cache/$CASE_CODE/config_options.json

          # Extract comments for documentation
          grep -E '^%.*' "$CONFIG_PATH" > .ci/cache/$CASE_CODE/config_comments.txt

          echo "$CASE_CODE" > .ci/cache/$CASE_CODE/case_code.txt
          echo "$CONFIG_PATH" > .ci/cache/$CASE_CODE/config_path.txt
          cp "$CONFIG_PATH" .ci/cache/$CASE_CODE/original_config.cfg

          echo "Committing metadata files to repo..."
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .ci/cache/$CASE_CODE/
          git commit -m "Cache config metadata for $CASE_CODE" || echo "No changes to commit"
          git push

      - name: Trigger config update workflow
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'update_config.yml',
              ref: 'main',
              inputs: {
                case_code: '${{ github.event.inputs.case_code }}'
              }
            })
