name: Select Validation Case

on:
  workflow_dispatch:
    inputs:
      case_code:
        description: "Enter the Validation Case Code (e.g., 2DZP)"
        required: true
        type: string

jobs:
  generate-inputs:
    runs-on: ubuntu-latest
    outputs:
      config_options: ${{ steps.parse-config.outputs.options }}
    steps:
      - uses: actions/checkout@v3

      - name: Parse config file
        id: parse-config
        run: |
          CONFIG_PATH="VandV/${{ inputs.case_code }}/config_sa_restart.cfg"
          if [ ! -f "$CONFIG_PATH" ]; then
            echo "::error::Config file not found at $CONFIG_PATH"
            exit 1
          fi

          # Extract all config options
          options=$(grep -E '^[^#%].*=' "$CONFIG_PATH" | awk -F '=' '{print $1}' | sed 's/ *$//')
          echo "options=$(echo $options | jq -R -s -c 'split(" ")')" >> $GITHUB_OUTPUT

      - name: Trigger update workflow
        uses: actions/github-script@v6
        with:
          script: |
            const { case_code } = context.payload.inputs;
            const options = "${{ steps.parse-config.outputs.options }}".split(',');

            // Create dynamic inputs object
            const inputs = {
              case_code: case_code
            };

            // Add all config options as potential inputs
            options.forEach(option => {
              if (option.trim()) {
                inputs[option.trim()] = '';
              }
            });

            // Trigger workflow with all possible inputs
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'update_config.yml',
              ref: 'main',
              inputs: inputs
            });
