name: Select Validation Case

on:
  workflow_dispatch:
    inputs:
      case_code:
        description: "Enter the Validation Case Code (e.g., 2DZP)"
        required: true
        type: string

jobs:
  trigger-next:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Trigger the update_config workflow
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # 👈 Required for auth
        run: |
          gh workflow run update_config.yml \
            -f case_code=${{ github.event.inputs.case_code }}
