name: Select Validation Case

on:
  workflow_dispatch:
    inputs:
      case_code:
        description: "Enter the Validation Case Code (e.g., 2DZP)"
        required: true
        type: string

jobs:
  generate-inputs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Parse config file
        id: parse-config
        run: |
          CONFIG_PATH="VandV/${{ inputs.case_code }}/config_sa_restart.cfg"
          if [ ! -f "$CONFIG_PATH" ]; then
            echo "::error::Config file not found at $CONFIG_PATH"
            exit 1
          fi

          # Create a JSON object with all config options
          echo "OPTIONS_JSON=$(grep -E '^[^#%].*=' "$CONFIG_PATH" | jq -R -n '[inputs | select(length>0) | split("=") | {"key": .[0] | gsub("^ +| +$";""), "value": (.[1:] | join("=") | gsub("^ +| +$";""))}]')" >> $GITHUB_ENV

      - name: Trigger update workflow
        uses: actions/github-script@v6
        with:
          script: |
            try {
              const options = JSON.parse(process.env.OPTIONS_JSON);
              const inputs = {
                case_code: '${{ inputs.case_code }}'
              };
              
              // Add all config options as potential inputs
              options.forEach(option => {
                if (option.key && option.key.trim()) {
                  inputs[option.key.trim()] = '';
                }
              });
              
              await github.rest.actions.createWorkflowDispatch({
                owner: context.repo.owner,
                repo: context.repo.repo,
                workflow_id: 'update_config.yml',
                ref: 'main',
                inputs: inputs
              });
            } catch (error) {
              core.setFailed(`Failed to trigger workflow: ${error.message}`);
            }
