name: Select Validation Case

on:
  workflow_dispatch:
    inputs:
      case_code:
        description: "Enter the Validation Case Code (e.g., 2DZP)"
        required: true
        type: string

jobs:
  generate-inputs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Parse config file
        id: parse-config
        run: |
          CONFIG_PATH="VandV/${{ inputs.case_code }}/config_sa_restart.cfg"
          if [ ! -f "$CONFIG_PATH" ]; then
            echo "::error::Config file not found at $CONFIG_PATH"
            exit 1
          fi

          # Create a JSON file with all config options
          grep -E '^[^#%].*=' "$CONFIG_PATH" | awk -F '=' '{print $1}' | sed 's/ *$//' | jq -R -s -c 'split("\n") | map(select(length > 0))' > config_options.json

          # Create a minimal workflow dispatch with just the case code
          echo "INPUT_JSON={\"case_code\":\"${{ inputs.case_code }}\"}" >> $GITHUB_ENV

      - name: Upload config options
        uses: actions/upload-artifact@v4
        with:
          name: config-options
          path: config_options.json

      - name: Trigger update workflow
        uses: actions/github-script@v6
        with:
          script: |
            try {
              await github.rest.actions.createWorkflowDispatch({
                owner: context.repo.owner,
                repo: context.repo.repo,
                workflow_id: 'update_config.yml',
                ref: 'main',
                inputs: JSON.parse(process.env.INPUT_JSON)
              });
            } catch (error) {
              core.error(`Failed to trigger workflow: ${error}`);
              throw error;
            }
