name: Update Config Options

on:
  workflow_dispatch:
    inputs:
      case_code:
        description: "Validation Case Code"
        required: true
        type: string

jobs:
  update-config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: config-data
          path: artifacts/

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Generate dynamic workflow
        run: |
          python .github/scripts/generate_workflow.py
          cat .github/workflows/dynamic_config.yml

      - name: Trigger dynamic workflow
        run: |
          gh workflow run dynamic_config.yml --ref main -f case_code="${{ env.CASE_CODE }}"
