name: Update Config Options

on:
  workflow_dispatch:
    inputs:
      case_code:
        description: "Validation Case Code"
        required: true
        type: string

jobs:
  update-config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Modify config file
        run: |
          CONFIG_PATH="VandV/${{ inputs.case_code }}/config_sa_restart.cfg"
          TMP_FILE=$(mktemp)

          # Get all inputs that were provided
          INPUT_KEYS=$(jq -r '.inputs | keys[]' "$GITHUB_EVENT_PATH" | grep -v 'case_code')

          # Process the config file
          while IFS= read -r line; do
            if [[ "$line" =~ ^[^#%].*= ]]; then
              key=$(echo "$line" | awk -F '=' '{print $1}' | sed 's/ *$//')
              # Check if this key was provided as input
              if echo "$INPUT_KEYS" | grep -q "^$key$"; then
                value="${{ github.event.inputs[key] }}"
                if [ -n "$value" ]; then
                  echo "$key = $value" >> "$TMP_FILE"
                  continue
                fi
              fi
            fi
            echo "$line" >> "$TMP_FILE"
          done < "$CONFIG_PATH"

          mv "$TMP_FILE" "$CONFIG_PATH"

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add VandV/${{ inputs.case_code }}/config_sa_restart.cfg
          git commit -m "Update config for ${{ inputs.case_code }}"
          git push
