name: Update Config Options

on:
  workflow_dispatch:
    inputs:
      case_code:
        description: "Validation Case Code"
        required: true
        type: string

jobs:
  update-config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: config-data
          path: artifacts/

      - name: Read config data
        id: read-config
        run: |
          CASE_CODE=$(cat artifacts/case_code.txt)
          CONFIG_PATH=$(cat artifacts/config_path.txt)
          echo "CASE_CODE=${CASE_CODE}" >> $GITHUB_ENV
          echo "CONFIG_PATH=${CONFIG_PATH}" >> $GITHUB_ENV
          echo "CONFIG_KEYS=$(cat artifacts/config_options.json)" >> $GITHUB_ENV

      - name: Generate dynamic workflow
        id: generate-workflow
        run: |
          # Install jq for JSON processing
          sudo apt-get install -y jq

          # Create basic workflow structure
          cat > .github/workflows/dynamic_config.yml << 'EOL'
          name: Dynamic Config Update
          on:
            workflow_dispatch:
              inputs:
                case_code:
                  description: "Validation Case Code"
                  required: true
                  type: string
          EOL

          # Add config options as inputs
          jq -r '.[]' artifacts/config_options.json | while read key; do
            cat >> .github/workflows/dynamic_config.yml << EOL
                ${key}:
                  description: "Set value for ${key}"
                  required: false
                  type: string
          EOL
          done

          # Add the jobs section
          cat >> .github/workflows/dynamic_config.yml << 'EOL'
          jobs:
            update-config-file:
              runs-on: ubuntu-latest
              steps:
                - uses: actions/checkout@v4
                
                - name: Update config file
                  run: |
                    CONFIG_PATH="VandV/${{ github.event.inputs.case_code }}/config_sa_restart.cfg"
                    cp artifacts/original_config.cfg "$CONFIG_PATH"
          EOL

          # Add the config update commands
          jq -r '.[]' artifacts/config_options.json | while read key; do
            # Escape special characters in the key for sed
            ESCAPED_KEY=$(printf '%s\n' "$key" | sed -e 's/[\/&]/\\&/g')
            cat >> .github/workflows/dynamic_config.yml << EOL
                    if [ -n "${{ github.event.inputs.${key} }}" ]; then
                      sed -i "s/^${ESCAPED_KEY} *=.*/${ESCAPED_KEY}= ${{ github.event.inputs.${key}}}/" "$CONFIG_PATH"
                    fi
          EOL
          done

          # Add the commit step
          cat >> .github/workflows/dynamic_config.yml << 'EOL'
                
                - name: Commit changes
                  run: |
                    git config --global user.name "GitHub Actions"
                    git config --global user.email "actions@github.com"
                    git add "VandV/${{ github.event.inputs.case_code }}/config_sa_restart.cfg"
                    git commit -m "Updated config for ${{ github.event.inputs.case_code }}"
                    git push
          EOL

      - name: Trigger dynamic workflow
        run: |
          gh workflow run dynamic_config.yml --ref main -f case_code="${{ env.CASE_CODE }}"
